let adminRecords = [];
const originalRender = render;
render = async function () {
  if (location.hash.slice(1).split('?')[0] === 'admin') return renderAdmin();
  return originalRender();
};
async function renderAdmin() {
  if (user?.role !== 'admin') { nav('dashboard'); return; }
  const [summary, records, imports, sources] = await Promise.all([api('/api/admin/summary'), api('/api/admin/records'), api('/api/admin/imports'), api('/api/admin/sources')]);
  adminRecords = records;
  A.innerHTML = `<h1>Admin Data Center</h1><p class="muted">Secure operational workspace for importing, reviewing, and managing Neon-backed mining records.</p><div class="stats"><div class="card">Imported records<div class="num">${summary.total}</div></div><div class="card">Pending review<div class="num gold">${summary.pending}</div></div><div class="card">Verified<div class="num green">${summary.verified}</div></div><div class="card">Recent imports<div class="num">${imports.length}</div></div></div><section class="card admin-section"><h2>Add or Edit Mining Record</h2><form class="admin-form" id="record-form">${adminFields()}<div class="wide admin-actions"><button class="primary" type="submit">Save Record</button><button type="button" onclick="adminClearForm()">Clear</button></div></form><div id="record-errors" class="danger"></div></section><section class="card admin-section"><h2>Import Data</h2><p class="muted">CSV, XLS, and XLSX are validated before any record is written. Duplicate licence numbers are skipped and reported.</p><div class="admin-actions"><label>Upload CSV / Excel<input id="import-file" type="file" accept=".csv,.xls,.xlsx"></label><button class="primary" onclick="adminImport('import-file')">Import records</button><label>Import coordinates<input id="coordinates-file" type="file" accept=".csv,.xls,.xlsx"></label><button onclick="adminImport('coordinates-file')">Import coordinates</button></div><pre id="import-result"></pre></section><section class="card admin-section"><h2>Review Pending Records</h2>${adminRecordRows(records.filter((record) => record.verification_status === 'pending'))}</section><section class="card admin-section"><h2>Manage Data Sources</h2><form class="admin-form" id="source-form"><label>Source name<input name="name" required></label><label>Authority<input name="authority"></label><label>HTTPS URL<input name="url" type="url" required></label><div class="wide admin-actions"><button class="primary">Add source</button></div></form>${sources.length ? `<ul>${sources.map((source) => `<li>${esc(source.name)} — ${esc(source.authority || 'Unspecified')}</li>`).join('')}</ul>` : '<p class="muted">No managed sources added yet.</p>'}</section><section class="card admin-section"><h2>Recent Imports</h2>${imports.length ? `<div class="table-wrap"><table class="table"><thead><tr><th>File</th><th>Received</th><th>Imported</th><th>Rejected</th></tr></thead><tbody>${imports.map((item) => `<tr><td>${esc(item.filename)}</td><td>${esc(item.created_at)}</td><td>${item.imported_count}</td><td>${item.rejected_count}</td></tr>`).join('')}</tbody></table></div>` : '<p class="muted">No imports yet.</p>'}</section>`;
  document.getElementById('record-form').onsubmit = adminSaveRecord;
  document.getElementById('source-form').onsubmit = adminSaveSource;
}
function adminFields() { return [['licence_no','Licence Number'],['operator','Operator'],['state','State'],['lga','LGA'],['commodities','Mineral / Commodities'],['latitude','Latitude'],['longitude','Longitude'],['title_type','Licence Type'],['status','Status'],['area_m2','Area (m²)'],['issue_date','Issue Date','date'],['expiry_date','Expiry Date','date'],['source','Source'],['source_url','Source URL','url'],['verification_status','Verification Status'],['last_verified_at','Last Verified Date','date'],['ai_score','AI Score','number']].map(([name,label,type='text']) => `<label>${label}<input name="${name}" type="${type}"></label>`).join('') + `<label class="wide">Geological Notes<textarea name="geological_notes"></textarea></label><label class="wide">Infrastructure Notes<textarea name="infrastructure_notes"></textarea></label><label class="wide">Risk Notes<textarea name="risk_notes"></textarea></label>`; }
function adminRecordRows(records) { return records.length ? `<div class="table-wrap"><table class="table"><thead><tr><th>Licence</th><th>Operator</th><th>State</th><th>Actions</th></tr></thead><tbody>${records.map((record) => `<tr><td>${esc(record.licence_no)}</td><td>${esc(record.operator)}</td><td>${esc(record.state)}</td><td><button onclick="adminEdit('${record.id}')">Edit</button><button class="primary" onclick="adminVerify('${record.id}','verified')">Verify</button><button onclick="adminVerify('${record.id}','rejected')">Reject</button></td></tr>`).join('')}</tbody></table></div>` : '<p class="muted">No pending records.</p>'; }
async function adminSaveRecord(event) { event.preventDefault(); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); try { const id = form.dataset.id; await api(id ? `/api/admin/records/${id}` : '/api/admin/records', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); toast('Record saved.'); renderAdmin(); } catch (error) { document.getElementById('record-errors').textContent = (error.errors || [error.message]).join(' '); } }
function adminEdit(id) { const record = adminRecords.find((item) => item.id === id); const form = document.getElementById('record-form'); if (!record || !form) return; Object.entries(record).forEach(([key, value]) => { const input = form.elements[key]; if (input) input.value = Array.isArray(value) ? value.join(', ') : value || ''; }); form.dataset.id = id; form.scrollIntoView({ behavior: 'smooth' }); }
function adminClearForm() { const form = document.getElementById('record-form'); form.reset(); delete form.dataset.id; }
async function adminVerify(id, verification_status) { try { await api(`/api/admin/records/${id}/verify`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ verification_status }) }); toast(`Record ${verification_status}.`); renderAdmin(); } catch (error) { toast(error.message); } }
async function adminImport(inputId) { const file = document.getElementById(inputId).files[0]; if (!file) { toast('Choose a CSV or Excel file first.'); return; } const contents = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.onerror = reject; reader.readAsDataURL(file); }); const coordinates = inputId === 'coordinates-file'; try { const result = await api(coordinates ? '/api/admin/import-coordinates' : '/api/admin/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ filename: file.name, contents }) }); document.getElementById('import-result').textContent = coordinates ? `Updated ${result.imported} coordinate records; ${result.rejected} licence numbers were not found.` : `Imported ${result.imported}; skipped ${result.rejected} duplicate licences.`; renderAdmin(); } catch (error) { document.getElementById('import-result').textContent = JSON.stringify(error.errors || error.message, null, 2); } }
async function adminSaveSource(event) { event.preventDefault(); try { await api('/api/admin/sources', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); toast('Data source added.'); renderAdmin(); } catch (error) { toast(error.message); } }
