const A=document.getElementById('app');let current=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(u,o){let r=await fetch(u,o);let j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
function toast(s){let x=document.getElementById('toast');x.textContent=s;x.style.display='block';setTimeout(()=>x.style.display='none',2500)}
function nav(p){location.hash=p;render()}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>nav(b.dataset.page));
async function dashboard(){let d=await api('/api/dashboard');A.innerHTML=`<h1>Mining Intelligence Dashboard</h1><div class="muted">Source-backed Nigerian mining opportunity intelligence.</div>
<div class="stats"><div class="card">Mining Titles<div class="num">${d.titles}</div></div><div class="card">Active Titles<div class="num green">${d.active}</div></div><div class="card">High Potential<div class="num gold">${d.high_potential}</div></div><div class="card">Verified Records<div class="num">${d.titles}</div></div></div>
<div class="grid"><div class="card"><h2>Top Opportunities</h2>${table(d.records)}</div><div class="card"><h2>AI Analyst</h2><p class="muted">Select any licence and generate a structured investment screening report with provenance, risks and diligence actions.</p><div class="actions"><button class="primary" onclick="nav('licences')">Analyse a Licence</button><button onclick="nav('map')">Open Mining Map</button><button onclick="exportData()">Export data</button></div></div></div>`}
function table(rs){if(!rs.length)return '<div class="empty">No records found.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Licence</th><th>State</th><th>Operator</th><th>Commodity</th><th>Status</th><th>Score</th><th></th></tr></thead><tbody>${rs.map(r=>`<tr><td><b>${esc(r.licence_no)}</b></td><td>${esc(r.state)}</td><td>${esc(r.operator)}</td><td>${esc(r.commodities.join(', '))}</td><td><span class="badge ${r.status==='expired'?'expired':''}">${esc(r.status)}</span></td><td class="score">${r.ai_score}/100</td><td><button onclick="openLicence('${encodeURIComponent(r.id)}')">Analyse</button></td></tr>`).join('')}</tbody></table></div>`}
async function licences(){A.innerHTML=`<h1>Mining Licence Search</h1><div class="muted">Search the controlled, source-backed licence dataset.</div><div class="card"><div class="search"><input id="q" aria-label="Search licences" placeholder="Licence / operator / keyword"><input id="state" aria-label="Filter by state" placeholder="State"><input id="commodity" aria-label="Filter by commodity" placeholder="Commodity"><select id="status" aria-label="Filter by status"><option value="">Any status</option><option value="active">Active</option><option value="expired">Expired</option></select><button class="primary" onclick="doSearch()">Search</button></div><div id="results"></div></div>`;doSearch()}
async function doSearch(){let q=encodeURIComponent(document.getElementById('q').value),s=encodeURIComponent(document.getElementById('state').value),c=encodeURIComponent(document.getElementById('commodity').value),st=encodeURIComponent(document.getElementById('status').value);let d=await api(`/api/licences?q=${q}&state=${s}&commodity=${c}&status=${st}`);document.getElementById('results').innerHTML=`<div class="muted">${d.count} result(s)</div>${table(d.results)}`}
async function openLicence(id){current=id;let d=await api('/api/licences/'+id);A.innerHTML=`<button onclick="nav('licences')">← Back to search</button><h1>${esc(d.record.licence_no)}</h1><div class="muted">${esc(d.record.operator)} · ${esc(d.record.state)} · ${esc(d.record.lga)}</div><div class="grid" style="margin-top:18px"><div class="card"><h2>Licence Details</h2><p><b>Status:</b> ${esc(d.record.status)}</p><p><b>Area:</b> ${Number(d.record.area_m2).toLocaleString()} m²</p><p><b>Commodities:</b> ${esc(d.record.commodities.join(', '))}</p><p><b>Source:</b> <a href="${esc(d.record.source_url)}" target="_blank">${esc(d.record.source)}</a></p><p><b>Verified:</b> ${esc(d.record.verified_at)}</p></div><div class="card report"><h2>AI Investment Screening</h2><div class="num ${d.analysis.score>=85?'green':'gold'}">${d.analysis.score}/100</div><p><b>${esc(d.analysis.decision)}</b></p><h3>Strengths</h3><ul>${d.analysis.strengths.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Risks</h3><ul>${d.analysis.risks.map(x=>`<li class="danger">${esc(x)}</li>`).join('')}</ul><h3>Diligence</h3><ul>${d.analysis.actions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><button class="primary" onclick="downloadReport('${id}')">Generate Report</button></div></div>`}
async function analyst(){A.innerHTML=`<h1>AI Mining Analyst</h1><div class="muted">Choose a licence to run the structured screening engine.</div><div class="card"><div id="analyst-list"></div></div>`;let d=await api('/api/licences');document.getElementById('analyst-list').innerHTML=table(d.results)}
async function reports(){A.innerHTML=`<h1>Investment Reports</h1><div class="muted">Generate a source-backed screening report from any licence.</div><div class="card"><p>Select a licence from Search or Analyst, then generate its report.</p><button class="primary" onclick="nav('licences')">Open Licence Search</button></div>`}
async function sources(){let ss=await api('/api/sources');A.innerHTML=`<h1>Official Data Sources</h1><div class="cards">${ss.map(s=>`<div class="card source"><h3>${esc(s.name)}</h3><p class="muted">${esc(s.authority)}</p><a href="${esc(s.url)}" target="_blank">Open official source ↗</a></div>`).join('')}</div><div class="card" style="margin-top:16px"><h2>Source Sync</h2><p class="muted">Checks public source pages and records HTTP status. It does not bypass protected systems.</p><button class="primary" onclick="syncSources()">Check Sources Now</button><pre id="syncout"></pre></div>`}
async function syncSources(){try{let d=await api('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});document.getElementById('syncout').textContent=JSON.stringify(d.results,null,2);toast('Source check completed')}catch(e){toast(e.message)}}
async function exportData(){try{let d=await api('/api/export');let blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nigeria-mining-intelligence-records.json';a.click();URL.revokeObjectURL(a.href);toast('Data export downloaded')}catch(e){toast(e.message)}}
async function mapPage(){A.innerHTML=`<h1>Mining Map</h1><div class="muted">State-level visualization of verified records. Markers represent state centroids—not licence polygons—until authoritative geometry is available.</div><div class="card" style="margin-top:16px"><div id="map" class="map"></div></div>`;let m=L.map('map').setView([9.1,8.7],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(m);let rs=await api('/api/map');rs.forEach(r=>L.circleMarker([r.lat,r.lon],{radius:8}).addTo(m).bindPopup(`<b>${esc(r.licence_no)}</b><br>${esc(r.state)} — ${esc(r.lga)}<br>${esc(r.operator)}<br>AI Score: ${r.ai_score}/100`))}
async function downloadReport(id){let d=await api('/api/report?id='+id);let w=window.open('','_blank');w.document.write(`<html><head><title>${esc(d.title)}</title><style>body{font-family:Arial;max-width:900px;margin:40px auto;line-height:1.6}h1{color:#17304d}.box{border:1px solid #ddd;padding:18px;border-radius:10px}li{margin:7px}</style></head><body><h1>${esc(d.title)}</h1><p>Generated: ${esc(d.generated_at)}</p><div class="box"><h2>${esc(d.record.licence_no)} — ${esc(d.record.operator)}</h2><p>State: ${esc(d.record.state)} | Status: ${esc(d.record.status)} | Score: <b>${d.analysis.score}/100</b></p><h3>Decision</h3><p>${esc(d.analysis.decision)}</p><h3>Strengths</h3><ul>${d.analysis.strengths.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Risks</h3><ul>${d.analysis.risks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Diligence Actions</h3><ul>${d.analysis.actions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Provenance</h3><p>${esc(d.analysis.provenance.source)} — ${esc(d.analysis.provenance.source_url)} — verified ${esc(d.analysis.provenance.verified_at)}</p></div><script>window.print()</script></body></html>`);w.document.close()}
async function downloadReport(id){let d=await api('/api/report?id='+encodeURIComponent(id));let w=window.open('','_blank');if(!w){toast('Please allow pop-ups to generate the report.');return}w.opener=null;w.document.write(`<html><head><title>${esc(d.title)}</title><style>body{font-family:Arial;max-width:900px;margin:40px auto;line-height:1.6}h1{color:#17304d}.box{border:1px solid #ddd;padding:18px;border-radius:10px}li{margin:7px}</style></head><body><h1>${esc(d.title)}</h1><p>Generated: ${esc(d.generated_at)}</p><div class="box"><h2>${esc(d.record.licence_no)} — ${esc(d.record.operator)}</h2><p>State: ${esc(d.record.state)} | Status: ${esc(d.record.status)} | Score: <b>${d.analysis.score}/100</b></p><h3>Decision</h3><p>${esc(d.analysis.decision)}</p><h3>Strengths</h3><ul>${d.analysis.strengths.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Risks</h3><ul>${d.analysis.risks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Diligence Actions</h3><ul>${d.analysis.actions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Provenance</h3><p>${esc(d.analysis.provenance.source)} — ${esc(d.analysis.provenance.source_url)} — verified ${esc(d.analysis.provenance.verified_at)}</p></div><script>window.print()</script></body></html>`);w.document.close()}
async function render(){let p=location.hash.slice(1)||'dashboard';try{if(p==='dashboard')await dashboard();else if(p==='licences')await licences();else if(p==='map')await mapPage();else if(p==='analyst')await analyst();else if(p==='reports')await reports();else if(p==='sources')await sources();else await dashboard()}catch(e){A.innerHTML=`<div class="card"><h2>Application error</h2><p>${esc(e.message)}</p></div>`}}
render();
