let gpsPreview = [];
const baseAdminRender = renderAdmin;
renderAdmin = async function () { await baseAdminRender(); if (user?.role !== 'admin') return; A.insertAdjacentHTML('beforeend', `<section class="card admin-section"><h2>GPS Field Data</h2><p class="muted">Import GPX, KML, or CSV from a field device such as GPS H1. Review points before saving; direct Bluetooth is intentionally adapter-ready for a future device integration.</p><div class="admin-form"><label>GPS file<input id="gps-file" type="file" accept=".gpx,.kml,.csv"></label><label>Default Field Site Name<input id="gps-site"></label><label>Default Sample ID<input id="gps-sample"></label><label>Default Mineral Observed<input id="gps-mineral"></label><label>GPS Source<input id="gps-source" value="GPS H1 file import"></label><label class="wide">Field Notes<textarea id="gps-notes"></textarea></label><label class="wide">Photos / Attachments (URLs, one per line)<textarea id="gps-attachments"></textarea></label><div class="wide admin-actions"><button class="primary" onclick="gpsPreviewFile()">Review GPS points</button><button onclick="gpsSaveReviewed()">Save reviewed points</button></div></div><pre id="gps-result"></pre><div id="gps-preview"></div></section>`); };
function readGpsFile(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.onerror = reject; reader.readAsDataURL(file); }); }
async function gpsPreviewFile() { const file = document.getElementById('gps-file').files[0]; if (!file) return toast('Choose a GPX, KML, or CSV file first.'); try { const result = await api('/api/admin/gps/preview', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ filename:file.name, contents:await readGpsFile(file) }) }); gpsPreview = result.points; document.getElementById('gps-preview').innerHTML = `<p class="muted">${gpsPreview.length} valid GPS points ready for review.</p>${gpsPreview.slice(0,100).map((point, index) => `<label><input type="checkbox" class="gps-select" data-index="${index}" checked> ${esc(point.field_site_name || 'Waypoint')} · ${point.latitude.toFixed(6)}, ${point.longitude.toFixed(6)}${point.nearby ? ' · nearby existing point' : ''}</label><br>`).join('')}`; } catch (error) { document.getElementById('gps-result').textContent = JSON.stringify(error.errors || error.message, null, 2); } }
function gpsFields(point) { const value = (id) => document.getElementById(id).value.trim(); return { ...point, field_site_name: point.field_site_name || value('gps-site'), sample_id: point.sample_id || value('gps-sample'), mineral_observed: point.mineral_observed || value('gps-mineral'), field_notes: point.field_notes || value('gps-notes'), attachments: value('gps-attachments').split(/\n|,/).map((item) => item.trim()).filter(Boolean), gps_source: value('gps-source') || point.gps_source }; }
async function gpsSaveReviewed() { const selected = [...document.querySelectorAll('.gps-select:checked')].map((node) => gpsFields(gpsPreview[Number(node.dataset.index)])); if (!selected.length) return toast('Review and select at least one point.'); const payload = { points:selected }; if (!navigator.onLine) { await gpsQueueAdd(payload); toast('Offline: GPS points queued for sync.'); return; } try { const result = await api('/api/admin/gps/points', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload) }); document.getElementById('gps-result').textContent = `Saved ${result.saved}; skipped ${result.skipped} duplicates.`; } catch (error) { await gpsQueueAdd(payload); toast('GPS points were queued for retry.'); } }
function gpsDb() { return new Promise((resolve, reject) => { const request = indexedDB.open('nmi-field-capture', 1); request.onupgradeneeded = () => request.result.createObjectStore('queue', { autoIncrement:true }); request.onsuccess = () => resolve(request.result); request.onerror = reject; }); }
async function gpsQueueAdd(payload) { const db = await gpsDb(); return new Promise((resolve, reject) => { const tx = db.transaction('queue','readwrite'); tx.objectStore('queue').add(payload); tx.oncomplete = resolve; tx.onerror = reject; }); }
async function gpsSyncQueue() { if (!navigator.onLine || user?.role !== 'admin') return; const db = await gpsDb(); const items = await new Promise((resolve, reject) => { const tx = db.transaction('queue','readonly'); const request = tx.objectStore('queue').getAll(); request.onsuccess = () => resolve(request.result); request.onerror = reject; }); for (const item of items) { try { await api('/api/admin/gps/points', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(item) }); } catch (_) { return; } } const tx = db.transaction('queue','readwrite'); tx.objectStore('queue').clear(); }
window.addEventListener('online', gpsSyncQueue);
