const crypto = require('node:crypto');
const { XMLParser } = require('fast-xml-parser');

const array = (value) => value === undefined ? [] : Array.isArray(value) ? value : [value];
const text = (value, max = 4000) => String(value ?? '').trim().slice(0, max);
const number = (value) => value === '' || value === undefined || value === null ? null : Number(value);

function validatePoint(input, format = 'manual') {
const point = { field_site_name: text(input.field_site_name ?? input.name ?? input.Name, 240) || null, sample_id: text(input.sample_id ?? input['Sample ID'], 120) || null, mineral_observed: text(input.mineral_observed ?? input['Mineral observed'], 240) || null, field_notes: text(input.field_notes ?? input.description ?? input['Field Notes'], 10000) || null, attachments: Array.isArray(input.attachments) ? input.attachments.map((item) => text(item, 2000)).filter(Boolean) : text(input.attachments ?? input['Photos/attachments'], 10000).split(/[,\n]/).map((item) => item.trim()).filter(Boolean), gps_source: text(input.gps_source ?? input['GPS Source'], 120) || 'file_import', source_format: format, latitude: number(input.latitude ?? input.lat ?? input.Latitude), longitude: number(input.longitude ?? input.lon ?? input.lng ?? input.Longitude), altitude_m: number(input.altitude_m ?? input.ele ?? input.altitude ?? input.Altitude), recorded_at: (input.recorded_at ?? input.time ?? input.timestamp ?? input['Date/Time']) || null, verification_status: text(input.verification_status ?? input['Verification Status'], 20).toLowerCase() || 'pending' };
  const errors = [];
  if (!Number.isFinite(point.latitude) || point.latitude < -90 || point.latitude > 90) errors.push('Latitude must be between -90 and 90.');
  if (!Number.isFinite(point.longitude) || point.longitude < -180 || point.longitude > 180) errors.push('Longitude must be between -180 and 180.');
  if (point.altitude_m !== null && !Number.isFinite(point.altitude_m)) errors.push('Altitude must be numeric.');
  if (!['pending', 'verified', 'rejected'].includes(point.verification_status)) errors.push('Verification Status must be pending, verified, or rejected.');
  if (point.recorded_at && Number.isNaN(Date.parse(point.recorded_at))) errors.push('Date/time is invalid.');
  return { valid: !errors.length, errors, point };
}
function parseGpx(xml) { const doc = new XMLParser({ ignoreAttributes: false, attributeNamePrefix: '' }).parse(xml).gpx || {}; const points = [...array(doc.wpt), ...array(doc.trk).flatMap((track) => array(track.trkseg).flatMap((segment) => array(segment.trkpt)))]; return points.map((item) => ({ latitude: item.lat, longitude: item.lon, altitude_m: item.ele, recorded_at: item.time, field_site_name: item.name, field_notes: item.desc, gps_source: 'gps_h1_gpx' })); }
function parseKml(xml) { const doc = new XMLParser({ ignoreAttributes: false }).parse(xml); const collect = (node, out = []) => { if (!node || typeof node !== 'object') return out; Object.entries(node).forEach(([key, value]) => { if (key === 'Placemark') array(value).forEach((mark) => { const coordinateSets = [mark?.Point?.coordinates, mark?.LineString?.coordinates].filter(Boolean); coordinateSets.forEach((set) => String(set).trim().split(/\s+/).forEach((entry) => { const coordinates = entry.split(','); if (coordinates.length >= 2) out.push({ longitude: coordinates[0], latitude: coordinates[1], altitude_m: coordinates[2] || null, field_site_name: mark.name, field_notes: mark.description, gps_source: 'gps_h1_kml' }); })); }); else array(value).forEach((item) => collect(item, out)); }); return out; }; return collect(doc); }
function parseFile(filename, contents) { const name = text(filename, 255).toLowerCase(); const buffer = Buffer.from(String(contents || ''), 'base64'); if (!buffer.length || buffer.length > 4 * 1024 * 1024) throw new Error('GPS upload must be between 1 byte and 4 MB.'); const raw = buffer.toString('utf8'); let rows; let format; if (name.endsWith('.gpx')) { rows = parseGpx(raw); format = 'gpx'; } else if (name.endsWith('.kml')) { rows = parseKml(raw); format = 'kml'; } else if (name.endsWith('.csv')) { const [header, ...lines] = raw.trim().split(/\r?\n/); const keys = header.split(',').map((key) => key.trim()); rows = lines.filter(Boolean).map((line) => Object.fromEntries(keys.map((key, index) => [key, line.split(',')[index] ?? '']))); format = 'csv'; } else throw new Error('Use GPX, KML, or CSV for GPS import.'); if (!rows.length || rows.length > 2000) throw new Error('GPS upload must contain 1–2,000 points.'); return rows.map((row, index) => ({ row: index + 1, ...validatePoint(row, format) })); }
function pointHash(point) { return crypto.createHash('sha256').update([point.latitude.toFixed(6), point.longitude.toFixed(6), point.recorded_at || '', point.sample_id || ''].join('|')).digest('hex'); }
module.exports = { parseFile, pointHash, validatePoint };
