const crypto = require('node:crypto');
const { records, sources } = require('./_lib/data');
const { analysis, freePreview, freeSearchResults, potentialLabel, score, search } = require('./_lib/intelligence');
const { configureResponse, rateLimit, routeFromRequest } = require('./_lib/http');
const { createSession, createUser, destroySession, isAdmin, isPremium, publicUser, requireUser, verifyUser } = require('./_lib/auth');
const { requireDatabase } = require('./_lib/db');
const { insertSql, insertValues, normaliseLicence, parseCoordinateImport, parseImport, validateRecord } = require('./_lib/admin-data');
const { parseFile: parseGpsFile, pointHash, validatePoint } = require('./_lib/gps-data');

const STATE_CENTROIDS = { Kogi: [7.8, 6.7], Nasarawa: [8.5, 8.2], Zamfara: [12.2, 6.2], Plateau: [9.2, 9.5], Osun: [7.6, 4.5], Kwara: [8.9, 4.5] };
const freeLimit = 3;
const errorBody = (error) => ({ error: process.env.NODE_ENV === 'development' ? error.message : (error.statusCode && error.statusCode < 500 ? error.message : 'The service could not complete this request.') });
const findRecord = (items, id) => items.find((item) => item.id === String(id));

async function checkSources() {
  return Promise.all(sources().map(async (source) => {
    const checked_at = new Date().toISOString();
    try { const response = await fetch(source.url, { method: 'HEAD', redirect: 'follow', signal: AbortSignal.timeout(8_000), headers: { 'User-Agent': 'Nigeria-Mining-Intelligence/1.1 (+source-health-check)' } }); return { source: source.id, status: response.status, content_type: response.headers.get('content-type') || '', checked_at }; }
    catch (_) { return { source: source.id, error: 'Source could not be reached', checked_at }; }
  }));
}
async function saveAnalysis(user, record) { await requireDatabase().query('INSERT INTO analysis_history (id, user_id, licence_id, score) VALUES ($1, $2, $3, $4)', [crypto.randomUUID(), user.id, record.id, score(record)]); }
function adminOnly(user, res) { if (!isAdmin(user)) { res.status(403).json({ error: 'Administrator access required.' }); return false; } return true; }
const near = (point, candidate) => Math.abs(point.latitude - candidate.latitude) < 0.0005 && Math.abs(point.longitude - candidate.longitude) < 0.0005;

module.exports = async (req, res) => {
  configureResponse(req, res);
  if (!rateLimit(req, res)) return;
  if (req.method === 'OPTIONS') return res.status(204).setHeader('Allow', 'GET, POST, DELETE, OPTIONS').end();
  const route = routeFromRequest(req);
  try {
    if (req.method === 'GET' && route === '/health') return res.status(200).json({ ok: true, service: 'Nigeria Mining Intelligence', version: '2.0.0' });
    if (req.method === 'GET' && route === '/metadata') return res.status(200).json({ product: 'Nigeria Mining Intelligence', version: '2.0.0', data_policy: 'source-backed and verification-aware', exact_polygons: false, full_national_dataset: false });
    if (req.method === 'GET' && route === '/sources') return res.status(200).json(sources());
    if (req.method === 'POST' && route === '/auth/signup') { const user = await createUser(req.body || {}); await createSession(user, res); return res.status(201).json({ user: publicUser(user) }); }
    if (req.method === 'POST' && route === '/auth/login') { const user = await verifyUser(req.body || {}); await createSession(user, res); return res.status(200).json({ user: publicUser(user) }); }
    if (req.method === 'POST' && route === '/auth/logout') { await destroySession(req, res); return res.status(204).end(); }
    if (req.method === 'GET' && route === '/auth/me') { const user = await requireUser(req, res); return user && res.status(200).json({ user: publicUser(user) }); }
    if (req.method === 'POST' && route === '/auth/forgot-password') return res.status(202).json({ message: 'If an account exists, reset instructions will be sent.' });

    const user = await requireUser(req, res);
    if (!user) return;
    const titleRecords = records();
    if (route === '/admin/summary' && req.method === 'GET') { if (!adminOnly(user, res)) return; const result = await requireDatabase().query("SELECT COUNT(*)::int AS total, COUNT(*) FILTER (WHERE verification_status = 'pending')::int AS pending, COUNT(*) FILTER (WHERE verification_status = 'verified')::int AS verified FROM mining_records"); return res.status(200).json(result.rows[0]); }
    if (route === '/admin/records' && req.method === 'GET') { if (!adminOnly(user, res)) return; const result = await requireDatabase().query('SELECT * FROM mining_records ORDER BY updated_at DESC LIMIT 100'); return res.status(200).json(result.rows); }
    if (route === '/admin/records' && req.method === 'POST') { if (!adminOnly(user, res)) return; const validated = validateRecord(req.body || {}); if (!validated.valid) return res.status(400).json({ error: 'Record validation failed.', errors: validated.errors }); try { const result = await requireDatabase().query(insertSql, insertValues(validated.record, user.id)); return res.status(201).json(result.rows[0]); } catch (error) { if (error.code === '23505') return res.status(409).json({ error: 'A record with this licence number already exists.' }); throw error; } }
    if (route.startsWith('/admin/records/') && route.endsWith('/verify') && req.method === 'POST') { if (!adminOnly(user, res)) return; const status = String(req.body?.verification_status || '').toLowerCase(); if (!['verified', 'rejected'].includes(status)) return res.status(400).json({ error: 'Verification status must be verified or rejected.' }); const id = route.split('/')[3]; const result = await requireDatabase().query('UPDATE mining_records SET verification_status = $1, last_verified_at = CURRENT_DATE, updated_by = $2, updated_at = NOW() WHERE id = $3 RETURNING *', [status, user.id, id]); return result.rows[0] ? res.status(200).json(result.rows[0]) : res.status(404).json({ error: 'Record not found.' }); }
    if (route.startsWith('/admin/records/') && req.method === 'PUT') { if (!adminOnly(user, res)) return; const validated = validateRecord(req.body || {}); if (!validated.valid) return res.status(400).json({ error: 'Record validation failed.', errors: validated.errors }); const id = route.split('/').pop(); const values = insertValues(validated.record, user.id); const result = await requireDatabase().query('UPDATE mining_records SET licence_no=$2, licence_no_normalized=$3, operator=$4, state=$5, lga=$6, commodities=$7::jsonb, latitude=$8, longitude=$9, title_type=$10, status=$11, area_m2=$12, issue_date=$13, expiry_date=$14, source=$15, source_url=$16, verification_status=$17, last_verified_at=$18, geological_notes=$19, infrastructure_notes=$20, risk_notes=$21, ai_score=$22, updated_by=$24, updated_at=NOW() WHERE id=$25 RETURNING *', [...values, id]); return result.rows[0] ? res.status(200).json(result.rows[0]) : res.status(404).json({ error: 'Record not found.' }); }
    if (route === '/admin/import' && req.method === 'POST') { if (!adminOnly(user, res)) return; const parsed = parseImport(req.body?.filename, req.body?.contents); const invalid = parsed.filter((item) => !item.valid); if (invalid.length) return res.status(400).json({ error: 'Import validation failed.', errors: invalid.map((item) => ({ row: item.row, errors: item.errors })) }); const db = requireDatabase(); const client = await db.connect(); try { await client.query('BEGIN'); const batchId = crypto.randomUUID(); await client.query('INSERT INTO import_batches (id, filename, record_count, created_by) VALUES ($1,$2,$3,$4)', [batchId, String(req.body?.filename || 'import').slice(0, 255), parsed.length, user.id]); let imported = 0; let rejected = 0; for (const item of parsed) { try { await client.query(insertSql, insertValues(item.record, user.id)); imported += 1; } catch (error) { if (error.code === '23505') rejected += 1; else throw error; } } await client.query('UPDATE import_batches SET imported_count=$1, rejected_count=$2 WHERE id=$3', [imported, rejected, batchId]); await client.query('COMMIT'); return res.status(201).json({ batch_id: batchId, imported, rejected }); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
    if (route === '/admin/import-coordinates' && req.method === 'POST') { if (!adminOnly(user, res)) return; const parsed = parseCoordinateImport(req.body?.contents); const invalid = parsed.filter((item) => !item.valid); if (invalid.length) return res.status(400).json({ error: 'Coordinate validation failed.', errors: invalid.map((item) => ({ row: item.row, errors: item.errors })) }); const db = requireDatabase(); const client = await db.connect(); try { await client.query('BEGIN'); const batchId = crypto.randomUUID(); await client.query('INSERT INTO import_batches (id, filename, record_count, created_by) VALUES ($1,$2,$3,$4)', [batchId, `Coordinates: ${String(req.body?.filename || 'import').slice(0, 240)}`, parsed.length, user.id]); let imported = 0; for (const item of parsed) { const result = await client.query('UPDATE mining_records SET latitude=$1, longitude=$2, updated_by=$3, updated_at=NOW() WHERE licence_no_normalized=$4', [item.record.latitude, item.record.longitude, user.id, normaliseLicence(item.record.licence_no)]); imported += result.rowCount; } const rejected = parsed.length - imported; await client.query('UPDATE import_batches SET imported_count=$1, rejected_count=$2 WHERE id=$3', [imported, rejected, batchId]); await client.query('COMMIT'); return res.status(201).json({ batch_id: batchId, imported, rejected }); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
    if (route === '/admin/imports' && req.method === 'GET') { if (!adminOnly(user, res)) return; const result = await requireDatabase().query('SELECT * FROM import_batches ORDER BY created_at DESC LIMIT 20'); return res.status(200).json(result.rows); }
    if (route === '/admin/sources' && req.method === 'GET') { if (!adminOnly(user, res)) return; const result = await requireDatabase().query('SELECT * FROM managed_data_sources ORDER BY updated_at DESC'); return res.status(200).json(result.rows); }
    if (route === '/admin/sources' && req.method === 'POST') { if (!adminOnly(user, res)) return; const name = String(req.body?.name || '').trim().slice(0, 240); const url = String(req.body?.url || '').trim().slice(0, 2000); if (!name || !/^https:\/\//i.test(url)) return res.status(400).json({ error: 'Source name and HTTPS URL are required.' }); const result = await requireDatabase().query('INSERT INTO managed_data_sources (id, name, authority, url, created_by) VALUES ($1,$2,$3,$4,$5) RETURNING *', [crypto.randomUUID(), name, String(req.body?.authority || '').trim().slice(0, 240) || null, url, user.id]); return res.status(201).json(result.rows[0]); }
    if (route === '/admin/gps/preview' && req.method === 'POST') { if (!adminOnly(user, res)) return; const parsed = parseGpsFile(req.body?.filename, req.body?.contents); const invalid = parsed.filter((item) => !item.valid); if (invalid.length) return res.status(400).json({ error: 'GPS validation failed.', errors: invalid.map((item) => ({ row: item.row, errors: item.errors })) }); const existing = await requireDatabase().query('SELECT latitude, longitude FROM gps_field_points UNION ALL SELECT latitude, longitude FROM mining_records WHERE latitude IS NOT NULL AND longitude IS NOT NULL'); return res.status(200).json({ points: parsed.map((item) => ({ ...item.point, nearby: existing.rows.some((candidate) => near(item.point, candidate)) })) }); }
    if (route === '/admin/gps/points' && req.method === 'POST') { if (!adminOnly(user, res)) return; const points = Array.isArray(req.body?.points) ? req.body.points.map((item) => validatePoint(item, item.source_format || 'field_capture')) : []; if (!points.length || points.length > 500) return res.status(400).json({ error: 'Save 1–500 reviewed GPS points at a time.' }); const invalid = points.filter((item) => !item.valid); if (invalid.length) return res.status(400).json({ error: 'GPS validation failed.', errors: invalid.map((item) => item.errors) }); const db = requireDatabase(); const client = await db.connect(); try { await client.query('BEGIN'); let saved = 0; let skipped = 0; for (const item of points) { const point = item.point; const result = await client.query('INSERT INTO gps_field_points (id, point_hash, field_site_name, sample_id, mineral_observed, field_notes, attachments, gps_source, source_format, latitude, longitude, altitude_m, recorded_at, verification_status, created_by) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT (point_hash) DO NOTHING', [crypto.randomUUID(), pointHash(point), point.field_site_name, point.sample_id, point.mineral_observed, point.field_notes, JSON.stringify(point.attachments), point.gps_source, point.source_format, point.latitude, point.longitude, point.altitude_m, point.recorded_at, point.verification_status, user.id]); saved += result.rowCount; skipped += result.rowCount ? 0 : 1; } await client.query('COMMIT'); return res.status(201).json({ saved, skipped }); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
    if (req.method === 'GET' && route === '/dashboard') { const results = search(titleRecords); return res.status(200).json({ titles: titleRecords.length, active: titleRecords.filter((record) => record.status === 'active').length, high_potential: titleRecords.filter((record) => score(record) >= 85).length, records: isPremium(user) ? results.slice(0, 8) : freeSearchResults(results, freeLimit), plan: user.role }); }
    if (req.method === 'GET' && route === '/licences') { const highPotential = String(req.query.high_potential || '').toLowerCase() === 'true'; const results = search(titleRecords, req.query).filter((record) => !highPotential || score(record) >= 85); const limited = !isPremium(user); return res.status(200).json({ count: results.length, results: limited ? freeSearchResults(results, freeLimit) : results, limited, plan: user.role, high_potential: highPotential }); }
    if (req.method === 'GET' && route.startsWith('/licences/')) { const record = findRecord(titleRecords, route.split('/').pop()); if (!record) return res.status(404).json({ error: 'Licence not found' }); if (!isPremium(user)) { const preview = freePreview(record); return res.status(200).json({ record: preview, analysis: { potential_label: preview.potential_label, decision: 'Upgrade to view the full AI analysis.', preview: true }, premium: false }); } return res.status(200).json({ record, analysis: analysis(record), premium: true }); }
    if (req.method === 'POST' && route === '/analyse') { const record = findRecord(titleRecords, req.body?.id) || titleRecords.find((item) => item.licence_no === req.body?.licence_no); if (!record) return res.status(404).json({ error: 'Licence not found' }); if (!isPremium(user)) return res.status(403).json({ error: 'Full AI analysis requires a Professional or Investor plan.', code: 'PREMIUM_REQUIRED' }); await saveAnalysis(user, record); return res.status(200).json(analysis(record)); }
    if (req.method === 'GET' && route === '/report') { const record = findRecord(titleRecords, req.query.id); if (!record) return res.status(404).json({ error: 'Licence not found' }); if (!isPremium(user)) return res.status(403).json({ error: 'Full reports require a Professional or Investor plan.', code: 'PREMIUM_REQUIRED' }); await requireDatabase().query('INSERT INTO reports (id, user_id, licence_id) VALUES ($1, $2, $3)', [crypto.randomUUID(), user.id, record.id]); return res.status(200).json({ title: 'Mining Investment Screening Report', generated_at: new Date().toISOString(), record, analysis: analysis(record) }); }
    if (req.method === 'GET' && route === '/map') { const gps = await requireDatabase().query("SELECT id, field_site_name, sample_id, mineral_observed, field_notes, latitude, longitude, altitude_m, recorded_at, verification_status FROM gps_field_points WHERE verification_status <> 'rejected'"); const titles = titleRecords.map((record) => { const point = STATE_CENTROIDS[record.state] || [9.1, 8.7]; const aiScore = score(record); return { ...record, lat: point[0], lon: point[1], ...(isPremium(user) ? { ai_score: aiScore } : { potential_label: potentialLabel(aiScore) }), geometry_quality: 'state_centroid', point_type: 'licence' }; }); const fieldPoints = gps.rows.map((point) => ({ ...point, lat: point.latitude, lon: point.longitude, point_type: 'field_gps', licence_no: point.field_site_name || 'Field GPS point', state: 'Field capture', lga: point.sample_id || '', operator: point.mineral_observed || '', ai_score: null })); return res.status(200).json([...titles, ...fieldPoints]); }
    if (req.method === 'GET' && route === '/export') { if (!isPremium(user)) return res.status(403).json({ error: 'Data exports require a Professional or Investor plan.', code: 'PREMIUM_REQUIRED' }); return res.status(200).json(titleRecords.map((record) => ({ ...record, ai_score: score(record) }))); }
    if (req.method === 'POST' && route.startsWith('/saved-licences/')) { if (!isPremium(user)) return res.status(403).json({ error: 'Saved opportunities require a Professional or Investor plan.', code: 'PREMIUM_REQUIRED' }); const id = route.split('/').pop(); if (!findRecord(titleRecords, id)) return res.status(404).json({ error: 'Licence not found' }); await requireDatabase().query('INSERT INTO saved_licences (user_id, licence_id) VALUES ($1, $2) ON CONFLICT DO NOTHING', [user.id, id]); return res.status(201).json({ saved: true }); }
    if (req.method === 'DELETE' && route.startsWith('/saved-licences/')) { await requireDatabase().query('DELETE FROM saved_licences WHERE user_id = $1 AND licence_id = $2', [user.id, route.split('/').pop()]); return res.status(204).end(); }
    if (req.method === 'GET' && route === '/saved-licences') { if (!isPremium(user)) return res.status(403).json({ error: 'Saved opportunities require a Professional or Investor plan.', code: 'PREMIUM_REQUIRED' }); const saved = await requireDatabase().query('SELECT licence_id, created_at FROM saved_licences WHERE user_id = $1 ORDER BY created_at DESC', [user.id]); return res.status(200).json(saved.rows.map((item) => ({ ...item, record: findRecord(titleRecords, item.licence_id) })).filter((item) => item.record)); }
    if (req.method === 'POST' && route === '/sync') { if (user.role !== 'admin') return res.status(403).json({ error: 'Administrator access required.' }); return res.status(200).json({ results: await checkSources(), note: 'Health check only. Protected systems are not bypassed; imported records require validation and review.' }); }
    res.setHeader('Allow', 'GET, POST, DELETE, OPTIONS');
    return res.status(404).json({ error: 'API route not found' });
  } catch (error) { console.error(error); return res.status(error.statusCode || 500).json(errorBody(error)); }
};

module.exports.config = { api: { bodyParser: { sizeLimit: '5mb' } } };
